interface TestParametersType {
	[key: string]: { param_name: string; default: boolean; }[];
}

export const TestParameters:TestParametersType = {
	'Base Oil': [
		{ param_name: 'Aluminium, Al', default: true },
		{ param_name: 'Antimony, Sb', default: true },
		{ param_name: 'Appearance', default: true },
		{ param_name: 'Barium, Ba', default: true },
		{ param_name: 'Boron, B', default: true },
		{ param_name: 'Cadmium, Cd', default: true },
		{ param_name: 'Calcium, Ca', default: true },
		{ param_name: 'Copper, Cu', default: true },
		{ param_name: 'Copper Corrosion', default: true },
		{ param_name: 'Density @ 15°C', default: true },
		{ param_name: 'Flash Point', default: true },
		{ param_name: 'Foaming - Sequence I', default: true },
		{ param_name: 'Foaming - Sequence II', default: true },
		{ param_name: 'Foaming - Sequence III', default: true },
		{ param_name: 'Iron, Fe', default: true },
		{ param_name: 'Kinematic Viscosity @ 100°C', default: true },
		{ param_name: 'Kinematic Viscosity @ 40°C', default: true },
		{ param_name: 'Lead, Pb', default: true },
		{ param_name: 'Lithium, Li', default: true },
		{ param_name: 'Magnesium, Mg', default: true },
		{ param_name: 'Manganese, Mn', default: true },
		{ param_name: 'Molybdenum, Mo', default: true },
		{ param_name: 'Nickel, Ni', default: true },
		{ param_name: 'Phosphorous, P', default: true },
		{ param_name: 'Potassium, K', default: true },
		{ param_name: 'Pour Point', default: true },
		{ param_name: 'Silicon, Si', default: true },
		{ param_name: 'Silver, Ag', default: true },
		{ param_name: 'Sodium, Na', default: true },
		{ param_name: 'Sulphated Ash', default: true },
		{ param_name: 'Tin, Sn', default: true },
		{ param_name: 'Titanium, Ti', default: true },
		{ param_name: 'Vanadium, V', default: true },
		{ param_name: 'Viscosity Index VI', default: true },
		{ param_name: 'Water (Karl Fischer)', default: true },
		{ param_name: 'Water Content', default: true },
		{ param_name: 'Zinc, Zn', default: true },
		{ param_name: 'Ash Content', default: false },
		{ param_name: 'Carbon, C', default: false },
		{ param_name: 'Carbon, C2', default: false },
		{ param_name: 'Chromium, Cr', default: false },
		{ param_name: 'Color', default: false },
		{ param_name: 'Hydrogen, H', default: false },
		{ param_name: 'Hydrogen, H2', default: false },
		{ param_name: 'ISO Particle Count', default: false },
		{ param_name: 'Particle Counting', default: false },
		{ param_name: 'Total Acid Number (TAN)', default: false },
		{ param_name: 'Total Base Number (TBN)', default: false }
	],
	'Coolant': [
		{ param_name: 'Appearance', default: true },
		{ param_name: 'Conductivity', default: true },
		{ param_name: 'Density @ 15°C', default: true },
		{ param_name: 'Freezing Point', default: true },
		{ param_name: 'Glycol Concentration', default: true },
		{ param_name: 'pH', default: true },
		{ param_name: 'Total Dissolved Solids (TDS)', default: true },
		{ param_name: 'Aluminium, Al', default: false },
		{ param_name: 'Antimony, Sb', default: false },
		{ param_name: 'Appearance', default: false },
		{ param_name: 'Barium, Ba', default: false },
		{ param_name: 'Boron, B', default: false },
		{ param_name: 'Cadmium, Cd', default: false },
		{ param_name: 'Calcium, Ca', default: false },
		{ param_name: 'Carbon, C', default: false },
		{ param_name: 'Carbon, C2', default: false },
		{ param_name: 'Chromium, Cr', default: false },
		{ param_name: 'Color', default: false },
		{ param_name: 'Copper, Cu', default: false },
		{ param_name: 'Foaming - Sequence I', default: false },
		{ param_name: 'Foaming - Sequence II', default: false },
		{ param_name: 'Foaming - Sequence III', default: false },
		{ param_name: 'Hydrogen, H', default: false },
		{ param_name: 'Hydrogen, H2', default: false },
		{ param_name: 'Iron, Fe', default: false },
		{ param_name: 'Kinematic Viscosity @ 100°C', default: false },
		{ param_name: 'Kinematic Viscosity @ 40°C', default: false },
		{ param_name: 'Lead, Pb', default: false },
		{ param_name: 'Lithium, Li', default: false },
		{ param_name: 'Magnesium, Mg', default: false },
		{ param_name: 'Manganese, Mn', default: false },
		{ param_name: 'Molybdenum, Mo', default: false },
		{ param_name: 'Nickel, Ni', default: false },
		{ param_name: 'Phosphorous, P', default: false },
		{ param_name: 'Potassium, K', default: false },
		{ param_name: 'Silicon, Si', default: false },
		{ param_name: 'Silver, Ag', default: false },
		{ param_name: 'Sodium, Na', default: false },
		{ param_name: 'Tin, Sn', default: false },
		{ param_name: 'Titanium, Ti', default: false },
		{ param_name: 'Vanadium, V', default: false },
		{ param_name: 'Zinc, Zn', default: false },
		{ param_name: 'Total Base Number (TBN)', default: false },
		{ param_name: 'Vanadium, V', default: false },
		{ param_name: 'Viscosity Index VI', default: false },
		{ param_name: 'Water (Karl Fischer)', default: false },
		{ param_name: 'Water Content', default: false }
	],
	'Compressor Oil': [
		{ param_name: 'Aluminium, Al', default: true },
		{ param_name: 'Antimony, Sb', default: true },
		{ param_name: 'Appearance', default: true },
		{ param_name: 'Barium, Ba', default: true },
		{ param_name: 'Boron, B', default: true },
		{ param_name: 'Cadmium, Cd', default: true },
		{ param_name: 'Calcium, Ca', default: true },
		{ param_name: 'Chromium, Cr', default: true },
		{ param_name: 'Color', default: true },
		{ param_name: 'Copper, Cu', default: true },
		{ param_name: 'Iron, Fe', default: true },
		{ param_name: 'Kinematic Viscosity @ 100°C', default: true },
		{ param_name: 'Kinematic Viscosity @ 40°C', default: true },
		{ param_name: 'Lead, Pb', default: true },
		{ param_name: 'Lithium, Li', default: true },
		{ param_name: 'Magnesium, Mg', default: true },
		{ param_name: 'Manganese, Mn', default: true },
		{ param_name: 'Molybdenum, Mo', default: true },
		{ param_name: 'Nickel, Ni', default: true },
		{ param_name: 'Phosphorous, P', default: true },
		{ param_name: 'Potassium, K', default: true },
		{ param_name: 'Silicon, Si', default: true },
		{ param_name: 'Silver, Ag', default: true },
		{ param_name: 'Sodium, Na', default: true },
		{ param_name: 'Tin, Sn', default: true },
		{ param_name: 'Titanium, Ti', default: true },
		{ param_name: 'Total Acid Number (TAN)', default: true },
		{ param_name: 'Vanadium, V', default: true },
		{ param_name: 'Viscosity Index VI', default: true },
		{ param_name: 'Water Content', default: true },
		{ param_name: 'Zinc, Zn', default: true },
		{ param_name: 'Carbon, C', default: false },
		{ param_name: 'Carbon, C2', default: false },
		{ param_name: 'Copper Corrosion', default: false },
		{ param_name: 'Demulsibility', default: false },
		{ param_name: 'Density @ 15°C', default: false },
		{ param_name: 'Di-electric Strength', default: false },
		{ param_name: 'Diesel', default: false },
		{ param_name: 'Ethylene Glycol', default: false },
		{ param_name: 'Flash Point', default: false },
		{ param_name: 'Foaming - Sequence I', default: false },
		{ param_name: 'Foaming - Sequence II', default: false },
		{ param_name: 'Foaming - Sequence III', default: false },
		{ param_name: 'Hydrogen, H', default: false },
		{ param_name: 'Hydrogen, H2', default: false },
		{ param_name: 'ISO Particle Count', default: false },
		{ param_name: 'MPC Varnish Potential,∆E', default: false },
		{ param_name: 'Nitration', default: false },
		{ param_name: 'Oxidation', default: false },
		{ param_name: 'Particle Counting', default: false },
		{ param_name: 'Pour Point', default: false },
		{ param_name: 'Ruler Test', default: false },
		{ param_name: 'Soot', default: false },
		{ param_name: 'Sulfation', default: false },
		{ param_name: 'Sulphated Ash', default: false },
		{ param_name: 'Total Base Number (TBN)', default: false },
		{ param_name: 'Water (FTIR)', default: false },
		{ param_name: 'Water (Karl Fischer)', default: false }
	],
	'Engine Oil': [
		{ param_name: 'Aluminium, Al', default: true },
		{ param_name: 'Antimony, Sb', default: true },
		{ param_name: 'Appearance', default: true },
		{ param_name: 'Barium, Ba', default: true },
		{ param_name: 'Boron, B', default: true },
		{ param_name: 'Cadmium, Cd', default: true },
		{ param_name: 'Calcium, Ca', default: true },
		{ param_name: 'Chromium, Cr', default: true },
		{ param_name: 'Copper, Cu', default: true },
		{ param_name: 'Iron, Fe', default: true },
		{ param_name: 'Kinematic Viscosity @ 100°C', default: true },
		{ param_name: 'Kinematic Viscosity @ 40°C', default: true },
		{ param_name: 'Lead, Pb', default: true },
		{ param_name: 'Lithium, Li', default: true },
		{ param_name: 'Magnesium, Mg', default: true },
		{ param_name: 'Manganese, Mn', default: true },
		{ param_name: 'Molybdenum, Mo', default: true },
		{ param_name: 'Nickel, Ni', default: true },
		{ param_name: 'Phosphorous, P', default: true },
		{ param_name: 'Potassium, K', default: true },
		{ param_name: 'Silicon, Si', default: true },
		{ param_name: 'Silver, Ag', default: true },
		{ param_name: 'Sodium, Na', default: true },
		{ param_name: 'Tin, Sn', default: true },
		{ param_name: 'Titanium, Ti', default: true },
		{ param_name: 'Total Acid Number (TAN)', default: true },
		{ param_name: 'Vanadium, V', default: true },
		{ param_name: 'Viscosity Index VI', default: true },
		{ param_name: 'Water Content', default: true },
		{ param_name: 'Zinc, Zn', default: true },
		{ param_name: 'Apparent Viscosity(CCS)', default: false },
		{ param_name: 'Carbon, C', default: false },
		{ param_name: 'Carbon, C2', default: false },
		{ param_name: 'Color', default: false },
		{ param_name: 'Copper Corrosion', default: false },
		{ param_name: 'Density @ 15°C', default: false },
		{ param_name: 'Diesel', default: false },
		{ param_name: 'Ethylene Glycol', default: false },
		{ param_name: 'Flash Point', default: false },
		{ param_name: 'Foaming - Sequence I', default: false },
		{ param_name: 'Foaming - Sequence II', default: false },
		{ param_name: 'Foaming - Sequence III', default: false },
		{ param_name: 'Hydrogen, H', default: false },
		{ param_name: 'Hydrogen, H2', default: false },
		{ param_name: 'Nitration', default: false },
		{ param_name: 'Oxidation', default: false },
		{ param_name: 'Pentane Insolubles', default: false },
		{ param_name: 'Pour Point', default: false },
		{ param_name: 'Soot', default: false },
		{ param_name: 'Sulfation', default: false },
		{ param_name: 'Sulphated Ash', default: false },
		{ param_name: 'Total Acid Number (TAN)', default: false },
		{ param_name: 'Water (FTIR)', default: false },
		{ param_name: 'Water (Karl Fischer)', default: false }
	],
	'Gear Oil': [
		{ param_name: 'Aluminium, Al', default: true },
		{ param_name: 'Antimony, Sb', default: true },
		{ param_name: 'Appearance', default: true },
		{ param_name: 'Barium, Ba', default: true },
		{ param_name: 'Boron, B', default: true },
		{ param_name: 'Cadmium, Cd', default: true },
		{ param_name: 'Calcium, Ca', default: true },
		{ param_name: 'Chromium, Cr', default: true },
		{ param_name: 'Copper, Cu', default: true },
		{ param_name: 'Iron, Fe', default: true },
		{ param_name: 'Kinematic Viscosity @ 100°C', default: true },
		{ param_name: 'Kinematic Viscosity @ 40°C', default: true },
		{ param_name: 'Lead, Pb', default: true },
		{ param_name: 'Lithium, Li', default: true },
		{ param_name: 'Magnesium, Mg', default: true },
		{ param_name: 'Manganese, Mn', default: true },
		{ param_name: 'Molybdenum, Mo', default: true },
		{ param_name: 'Nickel, Ni', default: true },
		{ param_name: 'Phosphorous, P', default: true },
		{ param_name: 'Potassium, K', default: true },
		{ param_name: 'Silicon, Si', default: true },
		{ param_name: 'Silver, Ag', default: true },
		{ param_name: 'Sodium, Na', default: true },
		{ param_name: 'Tin, Sn', default: true },
		{ param_name: 'Titanium, Ti', default: true },
		{ param_name: 'Vanadium, V', default: true },
		{ param_name: 'Viscosity Index VI', default: true },
		{ param_name: 'Water Content', default: true },
		{ param_name: 'Zinc, Zn', default: true },
		{ param_name: 'Brookfield Viscosity', default: false },
		{ param_name: 'Carbon, C', default: false },
		{ param_name: 'Carbon, C2', default: false },
		{ param_name: 'Color', default: false },
		{ param_name: 'Copper Corrosion', default: false },
		{ param_name: 'Density @ 15°C', default: false },
		{ param_name: 'Diesel', default: false },
		{ param_name: 'Ethylene Glycol', default: false },
		{ param_name: 'Flash Point', default: false },
		{ param_name: 'Foaming - Sequence I', default: false },
		{ param_name: 'Foaming - Sequence II', default: false },
		{ param_name: 'Foaming - Sequence III', default: false },
		{ param_name: 'Hydrogen, H', default: false },
		{ param_name: 'Hydrogen, H2', default: false },
		{ param_name: 'ISO Particle Count', default: false },
		{ param_name: 'Nitration', default: false },
		{ param_name: 'Oxidation', default: false },
		{ param_name: 'Pour Point', default: false },
		{ param_name: 'Soot', default: false },
		{ param_name: 'Sulfation', default: false },
		{ param_name: 'Sulphated Ash', default: false },
		{ param_name: 'Total Acid Number (TAN)', default: false },
		{ param_name: 'Total Base Number (TBN)', default: false },
		{ param_name: 'Water (FTIR)', default: false },
		{ param_name: 'Water (Karl Fischer)', default: false }
	],
	'Grease': [
		{ param_name: 'Dropping Point', default: true },
		{ param_name: 'Oil Separation @ 40°C, 42 Hrs', default: true },
		{ param_name: 'Worked Penetration @25°C', default: true }
	],
	'Hydraulic Oil': [
		{ param_name: 'Aluminium, Al', default: true },
		{ param_name: 'Antimony, Sb', default: true },
		{ param_name: 'Appearance', default: true },
		{ param_name: 'Barium, Ba', default: true },
		{ param_name: 'Boron, B', default: true },
		{ param_name: 'Cadmium, Cd', default: true },
		{ param_name: 'Calcium, Ca', default: true },
		{ param_name: 'Chromium, Cr', default: true },
		{ param_name: 'Copper, Cu', default: true },
		{ param_name: 'Iron, Fe', default: true },
		{ param_name: 'Kinematic Viscosity @ 100°C', default: true },
		{ param_name: 'Kinematic Viscosity @ 40°C', default: true },
		{ param_name: 'Lead, Pb', default: true },
		{ param_name: 'Lithium, Li', default: true },
		{ param_name: 'Magnesium, Mg', default: true },
		{ param_name: 'Manganese, Mn', default: true },
		{ param_name: 'Molybdenum, Mo', default: true },
		{ param_name: 'Nickel, Ni', default: true },
		{ param_name: 'Phosphorous, P', default: true },
		{ param_name: 'Potassium, K', default: true },
		{ param_name: 'Silicon, Si', default: true },
		{ param_name: 'Silver, Ag', default: true },
		{ param_name: 'Sodium, Na', default: true },
		{ param_name: 'Tin, Sn', default: true },
		{ param_name: 'Titanium, Ti', default: true },
		{ param_name: 'Total Acid Number (TAN)', default: true },
		{ param_name: 'Vanadium, V', default: true },
		{ param_name: 'Viscosity Index VI', default: true },
		{ param_name: 'Water Content', default: true },
		{ param_name: 'Zinc, Zn', default: true },
		{ param_name: 'Carbon, C', default: false },
		{ param_name: 'Carbon, C2', default: false },
		{ param_name: 'Color', default: false },
		{ param_name: 'Copper Corrosion', default: false },
		{ param_name: 'Demulsibility', default: false },
		{ param_name: 'Density @ 15°C', default: false },
		{ param_name: 'Di-electric Strength', default: false },
		{ param_name: 'Diesel', default: false },
		{ param_name: 'Ethylene Glycol', default: false },
		{ param_name: 'Flash Point', default: false },
		{ param_name: 'Foaming - Sequence I', default: false },
		{ param_name: 'Foaming - Sequence II', default: false },
		{ param_name: 'Foaming - Sequence III', default: false },
		{ param_name: 'Hydrogen, H', default: false },
		{ param_name: 'Hydrogen, H2', default: false },
		{ param_name: 'ISO Particle Count', default: false },
		{ param_name: 'MPC Varnish Potential,∆E', default: false },
		{ param_name: 'Nitration', default: false },
		{ param_name: 'Oxidation', default: false },
		{ param_name: 'Pour Point', default: false },
		{ param_name: 'Ruler Test', default: false },
		{ param_name: 'Soot', default: false },
		{ param_name: 'Sulfation', default: false },
		{ param_name: 'Sulphated Ash', default: false },
		{ param_name: 'Total Base Number (TBN)', default: false },
		{ param_name: 'Water (FTIR)', default: false },
		{ param_name: 'Water (Karl Fischer)', default: false }
	],
	'Transmission Oil': [
		{ param_name: 'Aluminium, Al', default: true },
		{ param_name: 'Antimony, Sb', default: true },
		{ param_name: 'Appearance', default: true },
		{ param_name: 'Barium, Ba', default: true },
		{ param_name: 'Boron, B', default: true },
		{ param_name: 'Cadmium, Cd', default: true },
		{ param_name: 'Calcium, Ca', default: true },
		{ param_name: 'Chromium, Cr', default: true },
		{ param_name: 'Copper, Cu', default: true },
		{ param_name: 'Iron, Fe', default: true },
		{ param_name: 'Kinematic Viscosity @ 100°C', default: true },
		{ param_name: 'Kinematic Viscosity @ 40°C', default: true },
		{ param_name: 'Lead, Pb', default: true },
		{ param_name: 'Lithium, Li', default: true },
		{ param_name: 'Magnesium, Mg', default: true },
		{ param_name: 'Manganese, Mn', default: true },
		{ param_name: 'Molybdenum, Mo', default: true },
		{ param_name: 'Nickel, Ni', default: true },
		{ param_name: 'Phosphorous, P', default: true },
		{ param_name: 'Potassium, K', default: true },
		{ param_name: 'Silicon, Si', default: true },
		{ param_name: 'Silver, Ag', default: true },
		{ param_name: 'Sodium, Na', default: true },
		{ param_name: 'Tin, Sn', default: true },
		{ param_name: 'Titanium, Ti', default: true },
		{ param_name: 'Vanadium, V', default: true },
		{ param_name: 'Viscosity Index VI', default: true },
		{ param_name: 'Water Content', default: true },
		{ param_name: 'Zinc, Zn', default: true },
		{ param_name: 'Brookfield Viscosity', default: false },
		{ param_name: 'Carbon, C', default: false },
		{ param_name: 'Carbon, C2', default: false },
		{ param_name: 'Color', default: false },
		{ param_name: 'Copper Corrosion', default: false },
		{ param_name: 'Density @ 15°C', default: false },
		{ param_name: 'Flash Point', default: false },
		{ param_name: 'Foaming - Sequence I', default: false },
		{ param_name: 'Foaming - Sequence II', default: false },
		{ param_name: 'Foaming - Sequence III', default: false },
		{ param_name: 'Hydrogen, H', default: false },
		{ param_name: 'Hydrogen, H2', default: false },
		{ param_name: 'Pour Point', default: false },
		{ param_name: 'Sulphated Ash', default: false },
		{ param_name: 'Total Acid Number (TAN)', default: false },
		{ param_name: 'Total Base Number (TBN)', default: false },
		{ param_name: 'Water (Karl Fischer)', default: false }
	],
	'Turbine Oil': [
		{ param_name: 'Aluminium, Al', default: true },
		{ param_name: 'Antimony, Sb', default: true },
		{ param_name: 'Appearance', default: true },
		{ param_name: 'Barium, Ba', default: true },
		{ param_name: 'Boron, B', default: true },
		{ param_name: 'Cadmium, Cd', default: true },
		{ param_name: 'Calcium, Ca', default: true },
		{ param_name: 'Chromium, Cr', default: true },
		{ param_name: 'Color', default: true },
		{ param_name: 'Copper, Cu', default: true },
		{ param_name: 'Foaming - Sequence I', default: true },
		{ param_name: 'Foaming - Sequence II', default: true },
		{ param_name: 'Foaming - Sequence III', default: true },
		{ param_name: 'Iron, Fe', default: true },
		{ param_name: 'Kinematic Viscosity @ 100°C', default: true },
		{ param_name: 'Kinematic Viscosity @ 40°C', default: true },
		{ param_name: 'Lead, Pb', default: true },
		{ param_name: 'Lithium, Li', default: true },
		{ param_name: 'Magnesium, Mg', default: true },
		{ param_name: 'Manganese, Mn', default: true },
		{ param_name: 'Molybdenum, Mo', default: true },
		{ param_name: 'MPC Varnish Potential,∆E', default: true },
		{ param_name: 'Nickel, Ni', default: true },
		{ param_name: 'Particle Counting', default: true },
		{ param_name: 'Phosphorous, P', default: true },
		{ param_name: 'Potassium, K', default: true },
		{ param_name: 'Silicon, Si', default: true },
		{ param_name: 'Silver, Ag', default: true },
		{ param_name: 'Sodium, Na', default: true },
		{ param_name: 'Tin, Sn', default: true },
		{ param_name: 'Titanium, Ti', default: true },
		{ param_name: 'Total Acid Number (TAN)', default: true },
		{ param_name: 'Vanadium, V', default: true },
		{ param_name: 'Viscosity Index VI', default: true },
		{ param_name: 'Water (Karl Fischer)', default: true },
		{ param_name: 'Zinc, Zn', default: true },
		{ param_name: 'Carbon, C', default: false },
		{ param_name: 'Carbon, C2', default: false },
		{ param_name: 'Copper Corrosion', default: false },
		{ param_name: 'Demulsibility', default: false },
		{ param_name: 'Density @ 15°C', default: false },
		{ param_name: 'Di-electric Strength', default: false },
		{ param_name: 'Flash Point', default: false },
		{ param_name: 'Hydrogen, H', default: false },
		{ param_name: 'Hydrogen, H2', default: false },
		{ param_name: 'ISO Particle Count', default: false },
		{ param_name: 'Oxidation', default: false },
		{ param_name: 'Pour Point', default: false },
		{ param_name: 'Ruler Test', default: false },
		{ param_name: 'Rust Prevention', default: false },
		{ param_name: 'Sulphated Ash', default: false },
		{ param_name: 'Total Base Number (TBN)', default: false },
		{ param_name: 'Water Content', default: false }
	],
	'Water Base Hydraulic': [
		{ param_name: 'ISO Particle Count', default: true },
		{ param_name: 'Particle Counting', default: true },
		{ param_name: 'Aluminium, Al', default: false },
		{ param_name: 'Antimony, Sb', default: false },
		{ param_name: 'Appearance', default: false },
		{ param_name: 'Ash Content', default: false },
		{ param_name: 'Barium, Ba', default: false },
		{ param_name: 'Boron, B', default: false },
		{ param_name: 'Cadmium, Cd', default: false },
		{ param_name: 'Calcium, Ca', default: false },
		{ param_name: 'Carbon, C', default: false },
		{ param_name: 'Carbon, C2', default: false },
		{ param_name: 'Chromium, Cr', default: false },
		{ param_name: 'Color', default: false },
		{ param_name: 'Copper, Cu', default: false },
		{ param_name: 'Density @ 15°C', default: false },
		{ param_name: 'Foaming - Sequence I', default: false },
		{ param_name: 'Foaming - Sequence II', default: false },
		{ param_name: 'Foaming - Sequence III', default: false },
		{ param_name: 'Hydrogen, H', default: false },
		{ param_name: 'Hydrogen, H2', default: false },
		{ param_name: 'Iron, Fe', default: false },
		{ param_name: 'Kinematic Viscosity @ 100°C', default: false },
		{ param_name: 'Kinematic Viscosity @ 40°C', default: false },
		{ param_name: 'Lead, Pb', default: false },
		{ param_name: 'Lithium, Li', default: false },
		{ param_name: 'Magnesium, Mg', default: false },
		{ param_name: 'Manganese, Mn', default: false },
		{ param_name: 'Molybdenum, Mo', default: false },
		{ param_name: 'Nickel, Ni', default: false },
		{ param_name: 'Phosphorous, P', default: false },
		{ param_name: 'Potassium, K', default: false },
		{ param_name: 'Silicon, Si', default: false },
		{ param_name: 'Silver, Ag', default: false },
		{ param_name: 'Sodium, Na', default: false },
		{ param_name: 'Tin, Sn', default: false },
		{ param_name: 'Titanium, Ti', default: false },
		{ param_name: 'Total Acid Number (TAN)', default: false },
		{ param_name: 'Total Base Number (TBN)', default: false },
		{ param_name: 'Vanadium, V', default: false },
		{ param_name: 'Zinc, Zn', default: false }
	]
}